[[[В порядке от наиболее интересных моих комментариев к менее интересным.]]]
Философские:
. ‘Лень — двигатель прогресса’[./len-dvigatel-progressa]

По программированию:
. ‘Философия языка’[./filosofiya-yazyka]
. ‘Признаки устаревшего языка’[./priznaki-ustarevshego-yazyka]
. ‘Выбор кодировки для компилятора’[./vybor-kodirovki-dlya-kompilyatora]

Смешанные:
. ‘Шестнадцатиричные и двоичные константы’[./shestnadtsatirichnye-i-dvoichnye-konstanty]
