[[[В порядке от наиболее интересных моих комментариев к менее интересным.]]]
Философские:
. ‘Лень — двигатель прогресса’[./len-dvigatel-progressa]

По программированию:
. ‘Философия языка’[./filosofiya-yazyka]
. ‘Признаки устаревшего языка’[./priznaki-ustarevshego-yazyka]
. ‘Выбор кодировки для компилятора’[./vybor-kodirovki-dlya-kompilyatora]
. ‘Переключатель’[./pereklyuchatel]
. ‘Десятка худших фич C#’[./desyatka-hudshih-fich-c-sharp]
. ‘Правила языка: строковые литералы’[./pravila-yazyka-strokovye-literaly]
. ‘К вопросу о парадигмах’[./k-voprosu-o-paradigmah]
. ‘Не поминайте всуе PL/1’[./ne-pominajte-vsue-pl1]
. ‘Заметки о выходе из функции без значения и зеркальности get и put’[./zametki-o-vyhode-iz-funktsii-bez-znacheniya-i-zerkalnosti-get-i-put]
. ‘О неправомерном доступе к памяти через указатели’[./o-nepravomernom-dostupe-k-pamyati-cherez-ukazateli]
. ‘Постфиксные инкремент и декремент’[./postfiksnye-inkrement-i-dekrement]
. ‘ЕС ЭВМ — это измена, трусость и обман?’[./es-evm-eto-izmena-trusost-i-obman]

Смешанные:
. ‘Шестнадцатиричные и двоичные константы’[./shestnadtsatirichnye-i-dvoichnye-konstanty]
